name: Lançamento de Nova Versão (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      base_branch:
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Definir versão
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Atualizar POM.XML (versão)
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "build: Nova Versão ${{ env.VERSION }}" || echo "Nada para commitar"
          git push

      - name: Build do projeto
        run: mvn clean install -DskipTests

      - name: Criar TAG
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Lançamento da Versão v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
